data_dir: /content/drive/MyDrive/CMU-MOSI
dataloaders:
  batch_size: 32
  num_workers: 1
  pin_memory: false
debug: false
device: cuda
experiment:
  description: MOSEI sentiment task
  name: mask_train-test-2
model:
  attention: true
  audio_input_size: 74
  audio_layers: 1
  augment_train_data: false
  bidirectional: true
  dropout: 0.2
  enable_plot_embeddings: true
  encoder_type: lstm
  feedback: true
  feedback_type: learnable_sequence_mask
  mask_dropout_test: 0.0
  mask_dropout_train: 0.0
  mask_index_test: 2
  mask_index_train: 2
  noise_modality: all
  noise_percentage_test: 0.0
  noise_percentage_train: 0.0
  noise_type: none
  projection_size: 100
  text_input_size: 300
  text_layers: 1
  visual_input_size: 35
  visual_layers: 1
num_classes: 1
optimizer:
  learning_rate: 0.0005
  name: Adam
overfit_batch: false
results_dir: /content/drive/MyDrive/our_results
test: true
train: true
trainer:
  checkpoint_dir: /home/geopar/projects/mm/clean_code/checkpoints
  load_model: mosei-sentiment-audio-text-visual_checkpoint.best.pth
  max_epochs: 100
  patience: 10
  retain_graph: true
