
                data_dir: /content/drive/MyDrive/CMU-MOSI
                results_dir: /content/drive/MyDrive/our_results
                train: true
                test: true
                overfit_batch: false
                debug: false
                device: cuda
                num_classes: 1

                model:
                text_input_size: 300
                audio_input_size: 74
                visual_input_size: 35
                projection_size: 100
                text_layers: 1
                audio_layers: 1
                visual_layers: 1
                bidirectional: true
                encoder_type: lstm
                dropout: !!float 0.2
                attention: true
                feedback: true
                feedback_type: learnable_sequence_mask
                mask_index_train: 1
                mask_index_test: 1
                mask_dropout_train: 0.0
                mask_dropout_test: 0.0
                noise_type: gaussian
                noise_percentage_train: 0.1
                noise_percentage_test: 0.0
                noise_modality: all
                enable_plot_embeddings: true

                experiment:
                name: noise_all_gaussian_high
                description: MOSEI sentiment task

                dataloaders:
                batch_size: 32
                num_workers: 1
                pin_memory: false

                optimizer:
                name: Adam
                learning_rate: !!float 5e-4

                trainer:
                patience: 10
                max_epochs: 100
                retain_graph: true
                load_model: mosei-sentiment-audio-text-visual_checkpoint.best.pth
                checkpoint_dir: /home/geopar/projects/mm/clean_code/checkpoints
                